Build/pipfile
pycontw/pycon-regbot pull request #6
Opened 2021-11-12 10:32 UTC by Darkborderman

## Types of changes
- **New feature**

## Description
Add package management tool.

## Related Issue
#5

2021-11-15 05:53 UTC, Darkborderman commented
@jordanSu Would you like to help me to review or assign others to review this pull request?

2021-11-15 06:07 UTC, jordanSu commented
@Darkborderman Yap sure, I will take a look and also assign one other member to review.

2021-11-15 06:17 UTC, Darkborderman commented
Thanks!

2021-11-16 06:07 UTC, josix approved these changes
LGTM!

2021-11-18 11:31 UTC, jordanSu requested changes

2021-11-18 11:31 UTC, jordanSu commented on sample.env
> +REG_BOT_SECRET=
```suggestion
```
Hello @Darkborderman,
I found you include the setup for ep-bot.py
And that remind me we actually haven't used it for a long time (maybe from the very beginning we didn't use it lol)
So I suggest not include setup for it, also I believe we can even delete `ep-bot.py` in this PR (or in another PR is also fine).

2021-11-18 18:07 UTC, Darkborderman commented on sample.env
> +REG_BOT_SECRET=
Sure, I'll remove `ep-bot.py` in another PR.  This PR will focus on `Pipfile` only.

2021-11-19 04:17 UTC, Darkborderman commented on sample.env
> +REG_BOT_SECRET=
Resolved.

2021-11-19 07:33 UTC, jordanSu approved these changes

2021-11-19 07:35 UTC, merged

2021-11-19 07:35 UTC, jordanSu commented
Thank you @Darkborderman !
It looks good now so I approved and merged.