Add detailed description on README
pycontw/pycon-regbot pull request #8
Opened 2021-11-23 13:08 UTC by Darkborderman

# Description
Add Update development and how to use on `README.md`.

# Fixes
fixes #3 .

2021-11-27 06:04 UTC, jordanSu approved these changes
LGTM! Thank you
Let me invite @josix , do you have any suggestions about what we can have for README?

2021-11-28 18:00 UTC, josix requested changes

2021-11-28 18:00 UTC, josix commented on README.md
> +to represent each ticket type.
NIT. I guess the order of the statements could be exchanged as follows:
```suggestion
to represent each ticket type:
* `corporate.csv` for corporate tickets
* `individual.csv` for individual tickets
* `reserved.csv` for reserved tickets
```

2021-11-29 15:44 UTC, Darkborderman commented on README.md
> +to represent each ticket type.
Resolved.

2021-11-29 16:34 UTC, josix approved these changes
LGTM, thanks @Darkborderman !

2021-11-29 16:34 UTC, merged